/** @format */

export const PokemonInfo = [
  {
    Nombre: "Aron",
    Tipo: "Stel, Rock",
    Numero: "#304",
    Habilidad: "Sturdy, Rock-Head",
    Peso: "60,0kg",
    Altura: "0,4m",
    HP: "050",
    ATK: "070",
    DEF: "100",
    STAK: "040",
    SDEF: "040",
    SPD: "030",
    id: 9,
    Img: "/Images/aron.png",
    Color: "#b7b9d0",
  },

  {
    Nombre: "Bulbasaur",
    Tipo: "Grass",
    Numero: "#001",
    Habilidad: "Chlorophyll, Overfrow",
    Peso: "6,9Kg",
    Altura: "0,7m",
    HP: "045",
    ATK: "049",
    DEF: "049",
    STAK: "065",
    SDEF: "065",
    SPD: "045",
    id: 1,
    Img: "/Images/bulbasaur.png",
    Color: "#74cb48",
  },

  {
    Nombre: "Butterfree",
    Tipo: "Bug",
    Numero: "#012",
    Habilidad: "Compound-Eyes, tinted-Lens",
    Peso: "32,0Kg",
    Altura: "1,1m",
    HP: "060",
    ATK: "045",
    DEF: "050",
    STAK: "090",
    SDEF: "080",
    SPD: "070",
    id: 4,
    Img: "/Images/butterfree.png",
    Color: "#a7b723",
  },

  {
    Nombre: "Charmander",
    Tipo: "Fire",
    Numero: "#004",
    Habilidad: "mega-punch, Fire-Punch",
    Peso: "8,5Kg",
    Altura: "0,5m",
    HP: "039",
    ATK: "052",
    DEF: "043",
    STAK: "060",
    SDEF: "050",
    SPD: "065",
    id: 2,
    Img: "/Images/charmander.png",
    Color: "#f57d31",
  },

  {
    Nombre: "Ditto",
    Tipo: "Normal",
    Numero: "#132",
    Habilidad: "Limber, Imposter",
    Peso: "4,0Kg",
    Altura: "0,3m",
    HP: "048",
    ATK: "048",
    DEF: "048",
    STAK: "048",
    SDEF: "048",
    SPD: "048",
    id: 7,
    Img: "/Images/ditto.png",
    Color: "#aaa67f",
  },

  {
    Nombre: "Gastly",
    Tipo: "Ghost",
    Numero: "#092",
    Habilidad: "Levitate",
    Peso: "0,1Kg",
    Altura: "1,3m",
    HP: "030",
    ATK: "035",
    DEF: "030",
    STAK: "100",
    SDEF: "035",
    SPD: "080",
    id: 6,
    Img: "/Images/gastly.png",
    Color: "#70559b",
  },

  {
    Nombre: "Mew",
    Tipo: "Psychic",
    Numero: "#152",
    Habilidad: "Synchronize",
    Peso: "4,0Kg",
    Altura: "0,4m",
    HP: "100",
    ATK: "100",
    DEF: "100",
    STAK: "100",
    SDEF: "100",
    SPD: "100",
    id: 8,
    Img: "/Images/mew.png",
    Color: "#fb5584",
  },

  {
    Nombre: "Pikachu",
    Tipo: "Electric",
    Numero: "#025",
    Habilidad: "Mega-Punch, Pay-Day",
    Peso: "6,0Kg",
    Altura: "0,4m",
    HP: "035",
    ATK: "055",
    DEF: "040",
    STAK: "050",
    SDEF: "050",
    SPD: "090",
    id: 5,
    Img: "/Images/pikachu.png",
    Color: "#f9cf30",
  },

  {
    Nombre: "Squirtle",
    Tipo: "Water",
    Numero: "#007",
    Habilidad: "Torrent, Rain-Dish",
    Peso: "9,0Kg",
    Altura: "0,5m",
    HP: "044",
    ATK: "048",
    DEF: "065",
    STAK: "050",
    SDEF: "064",
    SPD: "043",
    id: 3,
    Img: "/Images/squirtle.png",
    Color: "#6493eb",
  },
];

export default PokemonInfo;
